services:
    app:
        build: .
        container_name: "workout"
        restart: unless-stopped
        env_file: .env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/usr/src/app
